
{* **************************************************************************

 ===============================
 THINKING OF EDITING THE FOOTER?
 ===============================

Open Solutions and our staff have put a lot of time and effort into both
developing this web application and making it fit for public release under
the GPL license.

As such, we would appreciate and request you leave our copyright message and
link to our site intact in the footer so that we may in some small way
benefit from this application.

*************************************************************************** *}

{if !isset($inColorBox) || !$inColorBox}

    <div id="modal_dialog" class="modal hide fade"> </div>
    <footer>
        <p>
            Copyright &copy; 2014 - {$smarty.now|date_formatter:"%Y"} <a href="http://www.uniwire.cz/" target="_blank" title="UniWIRE Solution, s.r.o.">UniWIRE Solution, s.r.o.</a> MailAdmin V{ViMbAdmin_Version::VERSION}.
        </p>
        <p>
            Fork of <a href="http://www.vimbadmin.net/">ViMbAdmin</a> 
            Licensed under the <a href="http://www.gnu.org/licenses/gpl-3.0-standalone.html" target="_blank" title="GNU GPL v3">
                GNU General Public License V3
            </a>.
        </p>


    </footer>

{/if}

</div> <!-- .container -->

</body>

</html>
