{tmplinclude file="header.phtml"}

<div class="page-content" >

    <div class="page-header" >
        <h1>Změna hesla</h1>
    </div>

    {OSS_Message}

    <div class="row">

    <div class="span6 offset3">

    	<img src="{genUrl}/images/logo_500x159.jpg"  style="margin-bottom: 30px;"/>

        {$form}

        {addJSValidator form=$form}

        </div>
    </div>

</div>
{tmplinclude file="footer.phtml"}
