{tmplinclude file="header.phtml"}

<div class="page-content" >

    <div class="page-header" >
        <h1>Přihlášení do MailAdmin</h1>
    </div>

{OSS_Message}


{if isset( $loggedOut ) and $loggedOut}

<div id="vimbadmin-message-999" class="alert alert-success fade in">
    <a class="close" data-dismiss="alert" href="#">×</a>
    There is no admin to assign to this domain.
</div>

{/if}

<div class="row">

    <div class="span6 offset3">

    	<img src="{genUrl}/images/logo_500x159.jpg" style="margin-bottom: 30px;"/>

        <p>
        Vítejte v <em>ViMbAdmin</em>, webové aplikaci pro správu vašich mailových schránek a domén.
        </p>

        {$form}


        <div class="well">

            <p>
                Jste uživatel, nebo máte u nás mailovou schnku a chete zmenit vaše  <br />
                heslo? Pokud ano klikněte na tlačítko:

                <a style="float: right;" class="btn btn-primary" href="{genUrl controller="auth" action="change-password"}">Změnit heslo Mailové schránky</a>
            </p>

        </div>


    </div>
</div>

</div>

{tmplinclude file="footer.phtml"}
